// Schools list - Canadian schools first (focus on Ontario), then popular international schools
// Based on MLH schools list format

export const schools = [
  // Ontario Colleges (Conestoga and nearby)
  'Conestoga College',
  'Sheridan College',
  'Humber College',
  'George Brown College',
  'Seneca College',
  'Centennial College',
  'Mohawk College',
  'Fanshawe College',
  'Durham College',
  'Algonquin College',
  'Georgian College',
  'Niagara College',
  'Lambton College',
  'St. Clair College',
  'Loyalist College',
  'Fleming College',
  'Canadore College',
  'Cambrian College',
  'Confederation College',
  'Northern College',
  'Sault College',
  'La Cité collégiale',
  'Collège Boréal',
  
  // Ontario Universities
  'University of Waterloo',
  'Wilfrid Laurier University',
  'University of Toronto',
  'York University',
  'Toronto Metropolitan University',
  'McMaster University',
  'Western University',
  'Queen\'s University',
  'University of Ottawa',
  'Carleton University',
  'University of Guelph',
  'Ontario Tech University',
  'Brock University',
  'Trent University',
  'Lakehead University',
  'Laurentian University',
  'Nipissing University',
  'Algoma University',
  'OCAD University',
  
  // Other Canadian Universities
  'University of British Columbia',
  'Simon Fraser University',
  'University of Alberta',
  'University of Calgary',
  'McGill University',
  'Université de Montréal',
  'Concordia University',
  'Dalhousie University',
  'University of Manitoba',
  'University of Saskatchewan',
  'University of Victoria',
  'University of New Brunswick',
  'Memorial University',
  
  // US Universities (Popular)
  'Massachusetts Institute of Technology',
  'Stanford University',
  'Harvard University',
  'Carnegie Mellon University',
  'University of California, Berkeley',
  'Georgia Institute of Technology',
  'University of Michigan',
  'Cornell University',
  'Princeton University',
  'Columbia University',
  'University of Pennsylvania',
  'Yale University',
  'Duke University',
  'Northwestern University',
  'California Institute of Technology',
  'University of Illinois Urbana-Champaign',
  'University of Texas at Austin',
  'University of Washington',
  'Purdue University',
  'University of Southern California',
  'New York University',
  'University of California, Los Angeles',
  'University of California, San Diego',
  'Boston University',
  'University of Maryland',
  'Virginia Tech',
  'Penn State University',
  'Ohio State University',
  'University of Florida',
  'University of Wisconsin-Madison',
  'University of Minnesota',
  'Arizona State University',
  'University of Colorado Boulder',
  'Rice University',
  'Brown University',
  'Dartmouth College',
  
  // International
  'University of Oxford',
  'University of Cambridge',
  'Imperial College London',
  'ETH Zurich',
  'National University of Singapore',
  'University of Tokyo',
  'Tsinghua University',
  'Peking University',
  'Indian Institute of Technology',
  'University of Melbourne',
  'University of Sydney',
  
  // Other option
  'Other',
];

export type School = (typeof schools)[number];
